GET http://localhost:5276/games
//api for users
###
GET http://localhost:5276/games/1

###
POST http://localhost:5276/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 16.66,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5276/games/1
Content-Type: application/json

{
    "name": "Hot Mama",
    "genre": "Fiction",
    "price": 19.22,
    "releaseDate": "1992-07-15"
}