GET http://localhost:5276/games
//api for users
###
GET http://localhost:5276/games/4

###
POST http://localhost:5276/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 16.66,
    "releaseDate": "2011-11-18"
}